### ISSUE TITLE
missing rglwidget package in the plot3D example

### ISSUE THREAD

**Issue by smouksassi** [ua-snap/shiny-apps#115]
http://shiny.snap.uaf.edu/plot3D/ 
in the interactive tab there is an error about missing rglwidget package:

Error: This function requires the rglwidget package to be installed.

I just wanted to report it thanks for the great apps and examples

**Comment by leonawicz** [comment]
Thanks for the report. Yeah, this app has not been updated in some time. The joint handling of RGL and Shiny has changed a lot I think since I first made this app. rglwidget didn't exist at that time.

Regards,
Matt

**Comment by leonawicz** [comment]
I have cleaned up this app and removed any features of the app that are no longer supported. This includes a switch to the newer rglwidget package. The code here is updated, but if you want to see the app you have to access it here at this time: https://uasnap.shinyapps.io/plot3D/

Everything appears in order. I recommend using the volcano data set when exploring the RGL functionality at first. It's relatively small. The other data sets will work but may take a significant amount of time to process and show up in the brower, namely the hypsometry map which is a much larger data set.

**Comment by smouksassi** [comment]
Thanks for quick turn around and great examplesOne unrelated comment when the plot legend is not manual and we choose say position to be on top it does not work. Of course it works for manual mode.One thing I do is to hide these options when not relevant using conditionalpanel so user don't click a button or select an option that has no effect.Bests,Samer                                                                                                                                                                                                                From: Matt LeonawiczSent: Thursday, May 12, 2016 11:30To: ua-snap/shiny-appsReply To: ua-snap/shiny-appsCc: Samer Mouksassi; AuthorSubject: Re: [ua-snap/shiny-apps] missing rglwidget package in the plot3D example (#115)I have cleaned up this app and removed any features of the app that are no longer supported. This includes a switch to the newer rglwidget package. The code here is updated, but if you want to see the app you have to access it here at this time: https://uasnap.shinyapps.io/plot3D/

Everything appears in order. I recommend using the volcano data set when exploring the RGL functionality at first. It's relatively small. The other data sets will work but may take a significant amount of time to process and show up in the brower, namely the hypsometry map which is a much larger data set.

—You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub

**Comment by leonawicz** [comment]
Agreed. Removing as much confusion for the end user is ideal. I have one app with ~50 conditional panels among other tricks to improve reactive behavior and app usabilty. This app is just really really old. A lot of the apps in this repo were made when Shiny was still in alpha version. Many only have the appearance of being newer because I've done a minimal amount to keep them working as Shiny has evolved.

Here's an example of a newer app for comparison, which isn't a carry over from early Shiny versions. It also has some elements which appear only when relevant: https://uasnap.shinyapps.io/nwtapp/

By the way thank you for posting issues when you see them (Almost no one bothers to do this). I can't get to all the little fixes I'd like to unfortunately, but I would also do what I could to integrate any improvements via pull requests as well.

Regards,
Matt
